name: Go CI/CD

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.23.0'

        - name: Install dependencies
          run: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
            golangci-lint run ./...

        - name: Run unit tests
          run: go test -v ./...

        - name: Build Docker image
          run: docker build -t template .

        - name: Run Docker container
          run: |
            docker run -d -p 8080:8080 --name template-container template
            sleep 10

        - name: Install k6
          run: sudo apt install -y k6

        - name: Run k6 load test
          run: k6 run load_tests/hello_load_test.js

        - name: Stop and remove Docker container
          run: |
            docker stop my-template-app-container
            docker rm my-template-app-container